In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversedArr = arr[::-1]
print(reversedArr)

[5 4 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened1 = array1.flatten()
print(flattened1)

flattened2 = np.ravel(array1)
print(flattened2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)
print(are_equal)

True


In [ ]:
from collections import Counter
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_common1 = Counter(x).most_common(1)[0][0]
indices1 = np.where(x == most_common1)[0]
print("Most frequent in x:", most_common1)
print("Indices:", indices1)

most_common2 = Counter(y).most_common(1)[0][0]
indices2 = np.where(y == most_common2)[0]
print("Most frequent in y:", most_common2)
print("Indices:", indices2)

Most frequent in x: 1
Indices: [0 5 7 8 9]
Most frequent in y: 1
Indices: [0 1 2]


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)

print("Total sum:", total_sum)
print("Row-wise sum:\n", row_sum)
print("Column-wise sum:\n", col_sum)


Total sum: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]


In [ ]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

diag_sum = np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inv = np.linalg.inv(n_array)
det = np.linalg.det(n_array)

print("Diagonal sum:", diag_sum)
print("Eigenvalues:\n", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", inv)
print("Determinant:", det)


Diagonal sum: 176
Eigenvalues:
 [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [ ]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)
print(product1)
print(cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
print(product2)




[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
import itertools
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print(np.outer(x.flatten(),y.flatten()))
cartesian = np.array(list(itertools.product(x.flatten(),y.flatten())))
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)


flat = array.flatten()
q25 = np.percentile(flat, 25)
q50 = np.percentile(flat, 50)
q75 = np.percentile(flat, 75)
print(q25)
print(q50)
print(q75)

q25_col = np.percentile(array, 25, axis=0)
q50_col = np.percentile(array, 50, axis=0)
q75_col = np.percentile(array, 75, axis=0)
print(q25_col)
print(q50_col)
print(q75_col)

q25_row = np.percentile(array, 25, axis=1)
q50_row = np.percentile(array, 50, axis=1)
q75_row = np.percentile(array, 75, axis=1)
print(q25_row)
print(q50_row)
print(q75_row)


mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print(mean_flat)
print(median_flat)
print(std_flat)

mean_col = np.mean(array,axis=0)
median_col = np.median(array,axis=0)
std_col = np.std(array,axis=0)
print(mean_col)
print(median_col)
print(std_col)

mean_row = np.mean(array,axis=1)
median_row = np.median(array,axis=1)
std_row = np.std(array,axis=1)
print(mean_row)
print(median_row)
print(std_row)

[[1 2 3]
 [4 5 6]]
-3.5
-0.5
2.5
[-2.75 -0.25 -3.75]
[-1.5  1.5 -1.5]
[-0.25  3.25  0.75]
[-0.5 -5. ]
[ 1. -4.]
[2.  0.5]
-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor = np.floor(a)
ceil = np.ceil(a)
trunc = np.trunc(a)
round = np.round(a)
print(floor)
print(ceil)
print(trunc)
print(round)

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print(sorted_array)

sorted_indices = np.argsort(array)
print(sorted_indices)

smallest_4 = np.sort(array)[:4]
print(smallest_4)

largest_5 = np.sort(array)[-5:]
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [ ]:
a = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer = a == a.astype(int)
integer_element = a[integer]
print(integer_element)

float = a != a.astype(int)
float_element = a[float]
print(float_element)

[1. 2. 3. 2.]
[1.2 2.2]


In [ ]:
import os
from PIL import Image
from google.colab import files

def img_to_array(filename):
    img = Image.open(filename)
    arr = np.array(img)
    if img.mode == 'L':
        np.savetxt('image_gray.txt', arr, fmt='%d')
        print("Saved grayscale image to image_gray.txt")
    elif img.mode in ['RGB', 'RGBA']:
        arr_reshaped = arr.reshape(-1, arr.shape[2])
        np.savetxt('image_rgb.txt', arr_reshaped, fmt='%d')
        print("Saved RGB image to image_rgb.txt")

uploaded = files.upload()
if __name__ == "__main__":
    img_to_array('bg10.jpg')


Saving bg10.jpg to bg10 (1).jpg
Saved RGB image to image_rgb.txt
